language: scala
scala:
   - 2.11.7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
jdk:
  - oraclejdk8
script: sbt clean compile test:compile test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b7ababcafaa4747b3a7e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
